config/routes.rb
Rails.application.routes.draw do
  get 'welcome/home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#home'

  namespace :admin do
    resource :dashboards, only: :show
  end

  resources :authors, only: %i[index create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :music

    validates :name, presence: true

    def company
        "Sony"
    end
end

app/models/music.rb
class Music < ApplicationRecord
    belongs_to :author

    validates :title, :author, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    enum role: { normal: 0, admin: 1 }
end

app/controllers/admin/base_controller.rb
module Admin
    class BaseController < ApplicationController
        before_action :ensure_login!
        before_action :authenticate_admin!

        def ensure_login!
            redirect_to root_path unless current_user
        end

        def authenticate_admin!
            redirect_to root_path if !current_user.admin?
        end
    end
end

app/controllers/admin/dashboards_controller.rb
module Admin
    class DashboardsController < BaseController
        def show
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def current_user
        return nil unless session[:user_id]

        @current_user ||= User.find(session[:user_id])
    end

    helper_method :current_user
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
    def index
        @form = AuthorForm.new
        @authors = Author.all
    end

    def create
        @form = AuthorForm.new(form_params)

        if @form.save
            render :create
        else
            render :error
        end
    end

    private

    def form_params
        params.require(:author_form).permit(
            author_attributes: [:name],
            music_attributes: [:title],
        )
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/dashboards/show.html.erb
Only admins can see this

app/views/authors/_author_row.html.slim
tr
    td.border = author.name
    td.border = author.music.map(&:title).join(", ")

app/views/authors/_form.html.slim
= simple_form_for form, url: authors_path, method: :post, remote: true do |f|
    - if form.errors.any?
        .alert.alert-danger = form.errors.full_messages.join(", ")

    = form.title
    = f.simple_fields_for :author do |a|
        h1 Artist
        = a.input :name
    = f.simple_fields_for :music do |m|
        h1 Music
        = m.input :title
    = f.submit

app/views/authors/create.js.erb
$("#new_author_form").html("<%= j render "form", form: AuthorForm.new %>")
$("#authors tbody").prepend("<%= j render "author_row", author: @form.author %>")

app/views/authors/error.js.erb
$("#new_author_form").replaceWith("<%= j render "form", form: @form %>")

app/views/authors/index.html.slim
.px-24
    h1 This is Author index

    = render "form", form: @form

    table#authors.table
        thead
            tr
                th.border Name
                th.border Music
        tbody
            - @authors.each do |author|
                = render "author_row", author: author

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TailwindDemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'stylesheets', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/home.html.erb
<section class="mx-2 grid gap-3 grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
    <% 10.times do %>
        <div class="rounded overflow-hidden shadow-lg">
            <img class="w-full" src="https://images.unsplash.com/photo-1494548162494-384bba4ab999?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80" alt="Sunset in the mountains">
            <div class="px-6 py-4">
                <div class="font-bold text-xl mb-2">The Coldest Sunset</div>
                <p class="text-gray-700 text-base">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus quia, nulla! Maiores et perferendis eaque, exercitationem praesentium nihil.
                </p>
            </div>
            <div class="px-6 py-4">
                <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2">#photography</span>
                <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2">#travel</span>
                <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700">#winter</span>
            </div>
        </div>
    <% end %>
</section>